.PHONY: all clean example

all: example


example:
	make -C array
	make -C base
	make -C set
	make -C list
	make -C vector


clean:
	make -C array clean
	make -C base clean
	make -C set clean
	make -C list clean
	make -C vector clean

