.PHONY: all clean example

all: example


example:
	make -C array -f Makefile.gcc
	make -C base -f Makefile.gcc
	make -C set -f Makefile.gcc


clean:
	make -C array -f Makefile.gcc clean
	make -C base -f Makefile.gcc clean
	make -C set -f Makefile.gcc clean

