include ../gcc.mk


bin=stack



all: $(bin)

$(bin): main.o
	$(CXX) $(LDFLAGS) -o $(bin) main.o

main.o: main.cpp ../include/Cstack.h ../include/Cdynamicarray.h \
 ../include/Carray.h

clean:
	rm -f *.o $(bin)
