include ../gcc.mk

bin=stack_static


.PHONY: all clean

all: $(bin)

$(bin): main.o
	$(CXX) $(LDFLAGS) -o $(bin) main.o

main.o: main.cpp ../include/Cstack_static.h ../include/Cstaticarray.h \
 ../include/Carray.h

clean:
	rm -f *.o $(bin)
