CXX=g++
bin=stack_static
CXXFLAGS=-std=c++11 -g -Wall
LDFLAGS=

.PHONY: all clean

all: $(bin)

$(bin): main.o
	$(CXX) $(LDFLAGS) -o $(bin) main.o

main.o: main.cpp ../include/Cstack_static.h ../include/Cstaticarray.h \
 ../include/Carray.h

clean:
	rm -f *.o $(bin)
