bin=cirslinklist

CXX=g++
CXXFLAGS=-std=c++11  -pedantic -g -Wall
LDFLAGS=

.PHONY: all clean

all: $(bin)

$(bin): main.o
	$(CXX) $(LDFLAGS) -o $(bin) main.o

main.o: main.cpp ../include/Ccirlinklist.h ../include/Clinklist.h \
 ../include/Clist.h ../include/Cdynamicarray.h ../include/Carray.h

clean:
	rm -f *.o $(bin)
